server:
  port: 5000
  servlet:
    session:
      cookie:
        name: client2
security:
  oauth2:
    client:
      client-id: noel1
      client-secret: 123
      user-authorization-uri: http://localhost:5002/auth/oauth/authorize
      access-token-uri: http://localhost:5002/auth/oauth/token
    resource:
      user-info-uri: http://localhost:5002/auth/user
