server:
  port: 5002
  servlet:
    context-path: /auth

#######thymeleaf#########
# 模板的模式
spring:
  thymeleaf:
    cache: false # 这个开发配置为false，避免改了模板还要重启服务器
    mode: HTML5
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.31.76:3306/spring_oauth?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: auther
    password: 123123
#    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      init-s-q-l: SET NAMES utf8 COLLATION utf8_generial_ci
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  redis:
    port: 6379
    host: 192.168.31.76
    password: foobared
  main:
    allow-bean-definition-overriding: true
#######thymeleaf#########